services:
  backend:
    build: ./backend
    restart: always
    environment:
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_PORT=${DATABASE_PORT}
    ports:
      - "8000:8000"
    volumes:
      - ./backend/core:/code/core
      - ./backend/db:/code/db
    depends_on:
      database:
        condition: service_healthy
    tty: true

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"

  database:
    image: postgres:18.6-trixie
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  adminer:
    image: adminer:6.0.1-standalone
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
